#Bài 10: Kết quả của đoạn chương trình sau là gì?
try:
        print("throw")
except:
        print("except")
finally:
        print("finally")


#kết quả là throw và finally